version: 2

updates:
  - package-ecosystem: npm
    directory: /renderer
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(renderer)"

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(gradle)"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(actions)"
